meta_product_name: "PYC - Private Yacht Club"
meta_title: "PYC | Book, share & enjoy your sailing journey with sailors from all over the world"
meta_description: "Find the right companions to sail with, share the maintenance costs and explore the seas together !"
meta_image: "og.png" # should exist in `app/assets/images/`
